### ISSUE TITLE
Keras error when analyzing document with morfeusz-based models

### ISSUE THREAD

**Issue by dzieciou** [ipipan/spacy-pl#11]
I keep getting

```
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 282, in __init__
    raise ValueError(msg)
ValueError: Data cardinality is ambiguous:
  x sizes: 1, 6
Please provide data which shares the same first dimension.
```
when trying to parse a document 
```python
import spacy

nlp = spacy.load('pl_spacy_model_morfeusz_big')
for t in nlp("Mój kot wskoczył na półkę."):
    print(t)
```

The same problem happens also for `pl_spacy_model_morfeusz` model, but for `pl_spacy_model` everything works fine.

My setup:

Python 3.8

`requirements.txt`:

```
spacy==2.2
tensorflow-cpu==2.2
pl_spacy_model_morfeusz_big-0.1.0.tar.gz
pl_spacy_model_morfeusz-0.1.0.tar.gz
pl_spacy_model-0.1.0.tar.gz
```

morfeusz:
```
morfeusz2-0.4.0-py3.8-Linux-amd64.egg 
```

Full stacktrace:
```
Traceback (most recent call last):
  File "/home/dzieciou/projects/parsowanie-przepisow/proba.py", line 6, in <module>
    for t in nlp("Mój kot wskoczył na półkę."):
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/spacy/language.py", line 430, in __call__
    doc = self.make_doc(text)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/spacy/language.py", line 454, in make_doc
    return self.tokenizer(text)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/pl_spacy_model_morfeusz_big/preprocessor/__init__.py", line 234, in __call__
    return self.process(text)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/pl_spacy_model_morfeusz_big/preprocessor/__init__.py", line 203, in process
    tags = self.toygger.process(non_white_analysis, doc)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/pl_spacy_model_morfeusz_big/preprocessor/Toygger/__init__.py", line 95, in process
    predictions = self.model.predict(X)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1240, in predict
    data_handler = data_adapter.DataHandler(
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1100, in __init__
    self._adapter = adapter_cls(
  File "/home/dzieciou/venvs/przepisy-parsowanie/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 282, in __init__
    raise ValueError(msg)
ValueError: Data cardinality is ambiguous:
  x sizes: 1, 6
Please provide data which shares the same first dimension.
```

**Comment by ryszardtuora** [comment]
I'd wager that this must be related to some dependencies. I also have not tested this with Python 3.8. This occurs during regular task of processing a sentence right? At the moment I have little time, but I will look into it ASAP. Thanks for bringing it into my attention.

**Comment by dzieciou** [comment]
@ryszardtuora Yes, this happens during regular processing of a sentence. Would you be able to provide dependencies versions which worked for you? I could compare with mine and investigate.

In particular, could you provide me the output of the following commands:

```
python --version
python -m pip list 
```
and
```python
import morfeusz2
morfeusz2.Morfeusz().dict_id()
```
Perhaps there was some change in Morfeusz API, or Keras API...

**Comment by ryszardtuora** [comment]
Python version is `Python 3.6.9`, Morfeusz dict is `pl.sgjp.sgjp-2020.04.19`
These are my modules:
```
absl-py (0.9.0)
astor (0.8.1)
blis (0.4.1)
catalogue (1.0.0)
certifi (2020.6.20)
chardet (3.0.4)
cymem (2.0.3)
Distance (0.1.3)
gast (0.3.3)
google-pasta (0.2.0)
grpcio (1.29.0)
h5py (2.10.0)
idna (2.9)
importlib-metadata (1.6.1)
Keras (2.3.1)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.2)
Markdown (3.2.2)
morfeusz2 (0.4.0)
murmurhash (1.0.2)
numpy (1.18.4)
pip (9.0.1)
pkg-resources (0.0.0)
pl-spacy-model-morfeusz (0.1.0)
plac (1.1.3)
preshed (3.0.2)
protobuf (3.12.2)
PyYAML (5.3.1)
requests (2.24.0)
scipy (1.5.0)
setuptools (39.0.1)
six (1.15.0)
spacy (2.2.4)
srsly (1.0.2)
tensorboard (1.14.0)
tensorflow (1.14.0)
tensorflow-estimator (1.14.0)
termcolor (1.1.0)
thinc (7.4.0)
tqdm (4.46.1)
urllib3 (1.25.9)
wasabi (0.6.0)
Werkzeug (1.0.1)
wheel (0.34.2)
wrapt (1.12.1)
zipp (3.1.0)
``` 
I forgot to mention but the first thing to look at would probably be the spacy `2.2.4` version.

**Comment by dzieciou** [comment]
I've downgraded from tensorflow2 to tensorflow 1.14.0 as in your setup and now everything works fine. 

Thanks!

It would definitely help future users to use this great library, if all dependencies were listed in some form:
- as `requirements.txt` for `pip install` or
- as `environment.yml` for `conda install` or
- or simply as installation instructions.

It doesn't have to cover all possible configurations, just the one that worked for you.

**Comment by ryszardtuora** [comment]
Sure, we will include the requirements, but we plan to make the model up to date with newer versions of these libraries anyway, along with fixing some known bugs.
